services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: sqlserver_usersapi
    ports:
      - "1434:1433"
    environment:
      SA_PASSWORD: "Coti@2025"
      ACCEPT_EULA: "Y"
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: always

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq_usersapi
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    restart: always

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog_usersapi
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: always

volumes:
  sqlserver_data:
